### ISSUE TITLE
Issue: Evm Ext page not found

### ISSUE THREAD

**Issue by VictorTrustyDev** [evmos/docs#75]
Action: visit docs.evmos.org then search precompiles and click

Result: Navigated to https://docs.evmos.org/develop/build-a-dapp/build-smart-contracts/evm_extensions#further-reading but got Page Not Found

**Comment by GAtom22** [comment]
@VictorTrustyDev thanks for reporting this issue. Can you confirm this is still happening? because we made some changes to the structure and the search functionality takes some time to refresh. Now should be fixed

**Comment by VictorTrustyDev** [comment]
Thanks @GAtom22, it works now, I have tested few and all good 👍
